"""unittest functions.py"""
# pylint: disable=too-many-lines
from ipaddress import IPv4Network

IOS_ADDGR_CFG = """
hostname HOSTNAME

object-group network AG_NAME
  description TEXT
  host 10.0.0.1
  10.0.0.0 255.255.255.252
"""
CNX_ADDGR_WILD_252 = """
hostname HOSTNAME
object-group ip address AG_NAME
  0.0.0.0 255.255.255.252
"""

IOS_ACL_EXT_CFG = """
hostname HOSTNAME

object-group network AG_NAME
  10.0.0.0 255.255.255.0
  
ip access-list extended ACL_NAME
  remark === C-1
  permit tcp 10.0.0.1 0.0.0.0 eq 1 10.0.0.0 0.0.0.3 eq 2
  remark === C-2
  deny ip object-group AG_NAME any
  
interface Ethernet1/1
  ip access-group ACL_NAME in
"""

IOS_ACL_STD_CFG = """
hostname HOSTNAME

ip access-list standard ACL_NAME2
  remark === C-11
  permit host 10.0.0.1
  remark === C-12
  permit 10.0.0.0 0.0.0.3

interface Ethernet1/2
  ip access-group ACL_NAME2 in
  ip access-group ACL_NAME2 out
"""

IOS_ACL_WILD_252 = """
hostname HOSTNAME
ip access-list extended ACL_NAME
  permit ip 0.0.0.0 255.255.255.252 0.0.0.0 255.255.255.252
"""

CNX_ACL_EXT_CFG = """
hostname HOSTNAME

object-group ip address AG_NAME
  10 10.0.0.0 0.0.0.255

ip access-list ACL_NAME
  statistics per-entry
  10 remark === C-1
  20 permit tcp 10.0.0.1/32 eq 1 10.0.0.0/8 eq www
  30 remark === C-2
  40 deny ip addrgroup AG_NAME any

interface Ethernet1/1
  ip access-group ACL_NAME in
"""

IOS_ADDGR_D = [
    dict(line="object-group network AG_NAME\n  host 10.0.0.1\n  10.0.0.0 255.255.255.252",
         platform="ios",
         version="0",
         note="",
         indent="  ",
         name="AG_NAME",
         items=[
             dict(line="host 10.0.0.1",
                  platform="ios",
                  version="0",
                  items=[],
                  note="",
                  max_ncwb=16,
                  sequence=0,
                  type="host",
                  addrgroup="",
                  ipnet=IPv4Network("10.0.0.1/32"),
                  prefix="10.0.0.1/32",
                  subnet="10.0.0.1 255.255.255.255",
                  wildcard="10.0.0.1 0.0.0.0"),
             dict(line="10.0.0.0 255.255.255.252",
                  platform="ios",
                  version="0",
                  items=[],
                  note="",
                  max_ncwb=16,
                  sequence=0,
                  type="subnet",
                  addrgroup="",
                  ipnet=IPv4Network("10.0.0.0/30"),
                  prefix="10.0.0.0/30",
                  subnet="10.0.0.0 255.255.255.252",
                  wildcard="10.0.0.0 0.0.0.3"),
         ])
]
# noinspection DuplicatedCode
CNX_ACE_EXT_D = dict(
    line="ip access-list ACL_NAME\n"
         "  10 remark === C-1\n"
         "  20 permit tcp host 10.0.0.1 eq 1 10.0.0.0/8 eq www\n"
         "  30 remark === C-2\n"
         "  40 deny ip addrgroup AG_NAME any",
    platform="nxos",
    version="0",
    type="extended",
    input=["interface Ethernet1/1"],
    output=[],
    group_by="",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME",
    items=[
        dict(line="10 remark === C-1",
             platform="nxos",
             version="0",
             note="",
             sequence=10,
             action="remark",
             text="=== C-1"),
        dict(line="20 permit tcp host 10.0.0.1 eq 1 10.0.0.0/8 eq www",
             platform="nxos",
             version="0",
             type="extended",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=20,
             action="permit",
             protocol=dict(line="tcp",
                           platform="nxos",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=True,
                           name="tcp",
                           number=6),
             srcaddr=dict(line="host 10.0.0.1",
                          platform="nxos",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="host",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.1/32"),
                          prefix="10.0.0.1/32",
                          subnet="10.0.0.1 255.255.255.255",
                          wildcard="10.0.0.1 0.0.0.0"),
             srcport=dict(line="eq 1",
                          platform="nxos",
                          version="0",
                          note="",
                          protocol="tcp",
                          port_nr=False,
                          items=[1],
                          operator="eq",
                          ports=[1],
                          sport="1"),
             dstaddr=dict(line="10.0.0.0/8",
                          platform="nxos",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="prefix",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.0/8"),
                          prefix="10.0.0.0/8",
                          subnet="10.0.0.0 255.0.0.0",
                          wildcard="10.0.0.0 0.255.255.255"),
             dstport=dict(line="eq www",
                          platform="nxos",
                          version="0",
                          note="",
                          protocol="tcp",
                          port_nr=False,
                          items=[80],
                          operator="eq",
                          ports=[80],
                          sport="80"),
             option=dict(line="",
                         platform="nxos",
                         version="0",
                         note="",
                         flags=[],
                         logs=[])),
        dict(line="30 remark === C-2",
             platform="nxos",
             version="0",
             note="",
             sequence=30,
             action="remark",
             text="=== C-2"),
        dict(line="40 deny ip addrgroup AG_NAME any",
             platform="nxos",
             version="0",
             type="extended",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=40,
             action="deny",
             protocol=dict(line="ip",
                           platform="nxos",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=False,
                           name="ip",
                           number=0),
             srcaddr=dict(line="addrgroup AG_NAME",
                          platform="nxos",
                          version="0",
                          items=[
                              dict(line="10.0.0.0/24",
                                   platform="nxos",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="prefix",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.0/24"),
                                   prefix="10.0.0.0/24",
                                   subnet="10.0.0.0 255.255.255.0",
                                   wildcard="10.0.0.0 0.0.0.255"),
                          ],
                          note="",
                          max_ncwb=16,
                          type="addrgroup",
                          addrgroup="AG_NAME",
                          ipnet=None,
                          prefix="",
                          subnet="",
                          wildcard=""),
             srcport=dict(line="",
                          platform="nxos",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             dstaddr=dict(line="any",
                          platform="nxos",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="any",
                          addrgroup="",
                          ipnet=IPv4Network("0.0.0.0/0"),
                          prefix="0.0.0.0/0",
                          subnet="0.0.0.0 0.0.0.0",
                          wildcard="0.0.0.0 255.255.255.255"),
             dstport=dict(line="",
                          platform="nxos",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             option=dict(line="",
                         platform="nxos",
                         version="0",
                         note="",
                         flags=[],
                         logs=[])),
    ]
)

# noinspection DuplicatedCode
CNX_ACEG_EXT_D = dict(
    line="ip access-list ACL_NAME\n"
         "  10 remark === C-1\n"
         "  20 permit tcp host 10.0.0.1 eq 1 10.0.0.0/8 eq www\n"
         "  30 remark === C-2\n"
         "  40 deny ip addrgroup AG_NAME any",
    platform="nxos",
    version="0",
    type="extended",
    input=["interface Ethernet1/1"],
    output=[],
    name="ACL_NAME",
    items=[
        dict(line="10 remark === C-1\n20 permit tcp host 10.0.0.1 eq 1 10.0.0.0/8 eq www",
             platform="nxos",
             version="0",
             type="extended",
             name="=== C-1",
             items=[
                 dict(line="10 remark === C-1",
                      platform="nxos",
                      version="0",
                      note="",
                      sequence=10,
                      action="remark",
                      text="=== C-1"),
                 dict(line="20 permit tcp host 10.0.0.1 eq 1 10.0.0.0/8 eq www",
                      platform="nxos",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=20,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="nxos",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="host 10.0.0.1",
                                   platform="nxos",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="host",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.1/32"),
                                   prefix="10.0.0.1/32",
                                   subnet="10.0.0.1 255.255.255.255",
                                   wildcard="10.0.0.1 0.0.0.0"),
                      srcport=dict(line="eq 1",
                                   platform="nxos",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[1],
                                   operator="eq",
                                   ports=[1],
                                   sport="1"),
                      dstaddr=dict(line="10.0.0.0/8",
                                   platform="nxos",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="prefix",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.0/8"),
                                   prefix="10.0.0.0/8",
                                   subnet="10.0.0.0 255.0.0.0",
                                   wildcard="10.0.0.0 0.255.255.255"),
                      dstport=dict(line="eq www",
                                   platform="nxos",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[80],
                                   operator="eq",
                                   ports=[80],
                                   sport="80"),
                      option=dict(line="",
                                  platform="nxos",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]))],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="30 remark === C-2\n40 deny ip addrgroup AG_NAME any",
             platform="nxos",
             version="0",
             type="extended",
             name="=== C-2",
             items=[
                 dict(line="30 remark === C-2",
                      platform="nxos",
                      version="0",
                      note="",
                      sequence=30,
                      action="remark",
                      text="=== C-2"),
                 dict(line="40 deny ip addrgroup AG_NAME any",
                      platform="nxos",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=40,
                      action="deny",
                      protocol=dict(line="ip",
                                    platform="nxos",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="addrgroup AG_NAME",
                                   platform="nxos",
                                   version="0",
                                   items=[
                                       dict(line="10.0.0.0/24",
                                            platform="nxos",
                                            version="0",
                                            items=[],
                                            note="",
                                            max_ncwb=16,
                                            type="prefix",
                                            addrgroup="",
                                            ipnet=IPv4Network("10.0.0.0/24"),
                                            prefix="10.0.0.0/24",
                                            subnet="10.0.0.0 255.255.255.0",
                                            wildcard="10.0.0.0 0.0.0.255"),
                                   ],
                                   note="",
                                   max_ncwb=16,
                                   type="addrgroup",
                                   addrgroup="AG_NAME",
                                   ipnet=None,
                                   prefix="",
                                   subnet="",
                                   wildcard=""),
                      srcport=dict(line="",
                                   platform="nxos",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="nxos",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="nxos",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="nxos",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]))],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
    ],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
)
# noinspection DuplicatedCode
IOS_ACE_EXT_D = dict(
    line="ip access-list extended ACL_NAME\n"
         "  remark === C-1\n"
         "  permit tcp host 10.0.0.1 eq 1 10.0.0.0 0.0.0.3 eq 2\n"
         "  remark === C-2\n"
         "  deny ip object-group AG_NAME any",
    platform="ios",
    version="0",
    type="extended",
    input=["interface Ethernet1/1"],
    output=[],
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME",
    group_by="",
    items=[
        dict(line="remark === C-1",
             platform="ios",
             version="0",
             note="",
             sequence=0,
             action="remark",
             text="=== C-1"),
        dict(line="permit tcp host 10.0.0.1 eq 1 10.0.0.0 0.0.0.3 eq 2",
             platform="ios",
             version="0",
             type="extended",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=0,
             action="permit",
             protocol=dict(line="tcp",
                           platform="ios",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=True,
                           name="tcp",
                           number=6),
             srcaddr=dict(line="host 10.0.0.1",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="host",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.1/32"),
                          prefix="10.0.0.1/32",
                          subnet="10.0.0.1 255.255.255.255",
                          wildcard="10.0.0.1 0.0.0.0"),
             srcport=dict(line="eq 1",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="tcp",
                          port_nr=False,
                          items=[1],
                          operator="eq",
                          ports=[1],
                          sport="1"),
             dstaddr=dict(line="10.0.0.0 0.0.0.3",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="wildcard",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.0/30"),
                          prefix="10.0.0.0/30",
                          subnet="10.0.0.0 255.255.255.252",
                          wildcard="10.0.0.0 0.0.0.3"),
             dstport=dict(line="eq 2",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="tcp",
                          port_nr=False,
                          items=[2],
                          operator="eq",
                          ports=[2],
                          sport="2"),
             option=dict(line="",
                         platform="ios",
                         version="0",
                         note="",
                         flags=[],
                         logs=[])),
        dict(line="remark === C-2",
             platform="ios",
             version="0",
             note="",
             sequence=0,
             action="remark",
             text="=== C-2"),
        dict(line="deny ip object-group AG_NAME any",
             platform="ios",
             version="0",
             type="extended",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=0,
             action="deny",
             protocol=dict(line="ip",
                           platform="ios",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=False,
                           name="ip",
                           number=0),
             srcaddr=dict(line="object-group AG_NAME",
                          platform="ios",
                          version="0",
                          items=[
                              dict(line="10.0.0.0 0.0.0.255",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="wildcard",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.0/24"),
                                   prefix="10.0.0.0/24",
                                   subnet="10.0.0.0 255.255.255.0",
                                   wildcard="10.0.0.0 0.0.0.255"),
                          ],
                          note="",
                          max_ncwb=16,
                          type="addrgroup",
                          addrgroup="AG_NAME",
                          ipnet=None,
                          prefix="",
                          subnet="",
                          wildcard=""),
             srcport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             dstaddr=dict(line="any",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="any",
                          addrgroup="",
                          ipnet=IPv4Network("0.0.0.0/0"),
                          prefix="0.0.0.0/0",
                          subnet="0.0.0.0 0.0.0.0",
                          wildcard="0.0.0.0 255.255.255.255"),
             dstport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             option=dict(line="",
                         platform="ios",
                         version="0",
                         note="",
                         flags=[],
                         logs=[]))
    ]
)
# noinspection DuplicatedCode
IOS_ACEG_EXT_D = dict(
    line="ip access-list extended ACL_NAME\n"
         "  remark === C-1\n"
         "  permit tcp host 10.0.0.1 eq 1 10.0.0.0 0.0.0.3 eq 2\n"
         "  remark === C-2\n"
         "  deny ip object-group AG_NAME any",
    platform="ios",
    version="0",
    type="extended",
    input=["interface Ethernet1/1"],
    output=[],
    name="ACL_NAME",
    items=[
        dict(line="remark === C-1\npermit tcp host 10.0.0.1 eq 1 10.0.0.0 0.0.0.3 eq 2",
             platform="ios",
             version="0",
             type="extended",
             name="=== C-1",
             items=[
                 dict(line="remark === C-1",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== C-1"),
                 dict(line="permit tcp host 10.0.0.1 eq 1 10.0.0.0 0.0.0.3 eq 2",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="host 10.0.0.1",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="host",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.1/32"),
                                   prefix="10.0.0.1/32",
                                   subnet="10.0.0.1 255.255.255.255",
                                   wildcard="10.0.0.1 0.0.0.0"),
                      srcport=dict(line="eq 1",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[1],
                                   operator="eq",
                                   ports=[1],
                                   sport="1"),
                      dstaddr=dict(line="10.0.0.0 0.0.0.3",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="wildcard",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.0/30"),
                                   prefix="10.0.0.0/30",
                                   subnet="10.0.0.0 255.255.255.252",
                                   wildcard="10.0.0.0 0.0.0.3"),
                      dstport=dict(line="eq 2",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[2],
                                   operator="eq",
                                   ports=[2],
                                   sport="2"),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]),
                      ),
             ],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === C-2\ndeny ip object-group AG_NAME any",
             platform="ios",
             version="0",
             type="extended",
             name="=== C-2",
             items=[
                 dict(line="remark === C-2",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== C-2"),
                 dict(line="deny ip object-group AG_NAME any",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="deny",
                      protocol=dict(line="ip",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="object-group AG_NAME",
                                   platform="ios",
                                   version="0",
                                   items=[
                                       dict(line="10.0.0.0 0.0.0.255",
                                            platform="ios",
                                            version="0",
                                            items=[],
                                            note="",
                                            max_ncwb=16,
                                            type="wildcard",
                                            addrgroup="",
                                            ipnet=IPv4Network("10.0.0.0/24"),
                                            prefix="10.0.0.0/24",
                                            subnet="10.0.0.0 255.255.255.0",
                                            wildcard="10.0.0.0 0.0.0.255"),
                                   ],
                                   note="",
                                   max_ncwb=16,
                                   type="addrgroup",
                                   addrgroup="AG_NAME",
                                   ipnet=None,
                                   prefix="",
                                   subnet="",
                                   wildcard=""),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[])),
             ],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
    ],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
)
# noinspection DuplicatedCode
IOS_ACE_STD_D = dict(
    line="ip access-list standard ACL_NAME2\n"
         "  remark === C-11\n"
         "  permit host 10.0.0.1\n"
         "  remark === C-12\n"
         "  permit 10.0.0.0 0.0.0.3",
    platform="ios",
    version="0",
    type="standard",
    input=["interface Ethernet1/2"],
    output=["interface Ethernet1/2"],
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME2",
    group_by="",
    items=[
        dict(line="remark === C-11",
             platform="ios",
             version="0",
             note="",
             sequence=0,
             action="remark",
             text="=== C-11"),
        dict(line="permit host 10.0.0.1",
             platform="ios",
             version="0",
             type="standard",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=0,
             action="permit",
             protocol=dict(line="ip",
                           platform="ios",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=False,
                           name="ip",
                           number=0),
             srcaddr=dict(line="host 10.0.0.1",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="host",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.1/32"),
                          prefix="10.0.0.1/32",
                          subnet="10.0.0.1 255.255.255.255",
                          wildcard="10.0.0.1 0.0.0.0"),
             srcport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             dstaddr=dict(line="any",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="any",
                          addrgroup="",
                          ipnet=IPv4Network("0.0.0.0/0"),
                          prefix="0.0.0.0/0",
                          subnet="0.0.0.0 0.0.0.0",
                          wildcard="0.0.0.0 255.255.255.255"),
             dstport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             option=dict(line="",
                         platform="ios",
                         version="0",
                         note="",
                         flags=[],
                         logs=[])),
        dict(line="remark === C-12",
             platform="ios",
             version="0",
             note="",
             sequence=0,
             action="remark",
             text="=== C-12"),
        dict(line="permit 10.0.0.0 0.0.0.3",
             platform="ios",
             version="0",
             type="standard",
             note="",
             max_ncwb=16,
             protocol_nr=False,
             port_nr=False,
             sequence=0,
             action="permit",
             protocol=dict(line="ip",
                           platform="ios",
                           version="0",
                           note="",
                           protocol_nr=False,
                           has_port=False,
                           name="ip",
                           number=0),
             srcaddr=dict(line="10.0.0.0 0.0.0.3",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="wildcard",
                          addrgroup="",
                          ipnet=IPv4Network("10.0.0.0/30"),
                          prefix="10.0.0.0/30",
                          subnet="10.0.0.0 255.255.255.252",
                          wildcard="10.0.0.0 0.0.0.3"),
             srcport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             dstaddr=dict(line="any",
                          platform="ios",
                          version="0",
                          items=[],
                          note="",
                          max_ncwb=16,
                          type="any",
                          addrgroup="",
                          ipnet=IPv4Network("0.0.0.0/0"),
                          prefix="0.0.0.0/0",
                          subnet="0.0.0.0 0.0.0.0",
                          wildcard="0.0.0.0 255.255.255.255"),
             dstport=dict(line="",
                          platform="ios",
                          version="0",
                          note="",
                          protocol="",
                          port_nr=False,
                          items=[],
                          operator="",
                          ports=[],
                          sport=""),
             option=dict(line="",
                         platform="ios",
                         version="0",
                         note="",
                         flags=[],
                         logs=[]))
    ]
)
# noinspection DuplicatedCode
IOS_ACEG_STD_D = dict(
    line="ip access-list standard ACL_NAME2\n"
         "  remark === C-11\n"
         "  permit host 10.0.0.1\n"
         "  remark === C-12\n"
         "  permit 10.0.0.0 0.0.0.3",
    platform="ios",
    version="0",
    type="standard",
    input=["interface Ethernet1/2"],
    output=["interface Ethernet1/2"],
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME2",
    group_by="=== ",
    items=[
        dict(line="remark === C-11\npermit host 10.0.0.1",
             platform="ios",
             version="0",
             type="standard",
             name="=== C-11",
             group_by="=== ",
             items=[
                 dict(line="remark === C-11",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== C-11"),
                 dict(line="permit host 10.0.0.1",
                      platform="ios",
                      version="0",
                      type="standard",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="ip",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="host 10.0.0.1",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="host",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.1/32"),
                                   prefix="10.0.0.1/32",
                                   subnet="10.0.0.1 255.255.255.255",
                                   wildcard="10.0.0.1 0.0.0.0"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]))],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === C-12\npermit 10.0.0.0 0.0.0.3",
             platform="ios",
             version="0",
             type="standard",
             name="=== C-12",
             group_by="=== ",
             items=[
                 dict(line="remark === C-12",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== C-12"),
                 dict(line="permit 10.0.0.0 0.0.0.3",
                      platform="ios",
                      version="0",
                      type="standard",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="ip",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="10.0.0.0 0.0.0.3",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="wildcard",
                                   addrgroup="",
                                   ipnet=IPv4Network("10.0.0.0/30"),
                                   prefix="10.0.0.0/30",
                                   subnet="10.0.0.0 255.255.255.252",
                                   wildcard="10.0.0.0 0.0.0.3"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[])),
             ],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0)
    ]
)
