"""Unittest acl.py"""

from ipaddress import IPv4Network

import dictdiffer  # type: ignore

LINE_GROUP_ACEGS = """
ip access-list extended ACL_NAME
  permit icmp any any
  remark === NAME1
  permit tcp any any eq 1
  remark TEXT1
  remark === NAME2
  permit tcp any any eq 2
  deny ip any any
""".strip()
REQ_GROUPS_ACEGS_D = dict(
    line=LINE_GROUP_ACEGS,
    platform="ios",
    version="0",
    type="extended",
    input=[],
    output=[],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME",
    items=[
        dict(line="permit icmp any any",
             platform="ios",
             version="0",
             type="extended",
             name="",
             group_by="=== ",
             items=[
                 dict(line="permit icmp any any",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="icmp",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="icmp",
                                    number=1),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]))],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME1\npermit tcp any any eq 1\nremark TEXT1",
             platform="ios",
             version="0",
             type="extended",
             name="=== NAME1",
             group_by="=== ",
             items=[
                 dict(line="remark === NAME1",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME1"),
                 dict(line="permit tcp any any eq 1",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="eq 1",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[1],
                                   operator="eq",
                                   ports=[1],
                                   sport="1"),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[])),
                 dict(line="remark TEXT1",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="TEXT1")],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME2\npermit tcp any any eq 2\ndeny ip any any",
             platform="ios",
             version="0",
             type="extended",
             name="=== NAME2",
             group_by="=== ",
             items=[
                 dict(line="remark === NAME2",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME2"),
                 dict(line="permit tcp any any eq 2",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="eq 2",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[2],
                                   operator="eq",
                                   ports=[2],
                                   sport="2"),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[])),
                 dict(line="deny ip any any",
                      platform="ios",
                      version="0",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="deny",
                      protocol=dict(line="ip",
                                    platform="ios",
                                    version="0",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   version="0",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   version="0",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="",
                                  platform="ios",
                                  version="0",
                                  note="",
                                  flags=[],
                                  logs=[]))],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
    ]
)

LINE_GROUP_REMARKS = """
ip access-list extended ACL_NAME
  remark === NAME1
  remark === NAME2
""".strip()
REQ_GROUP_REMARKS_D = dict(
    line=LINE_GROUP_REMARKS,
    platform="ios",
    version="0",
    type="extended",
    input=[],
    output=[],
    name="ACL_NAME",
    items=[
        dict(line="remark === NAME1",
             platform="ios",
             version="0",
             type="extended",
             name="=== NAME1",
             items=[
                 dict(line="remark === NAME1",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME1")],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME2",
             platform="ios",
             version="0",
             type="extended",
             name="=== NAME2",
             items=[
                 dict(line="remark === NAME2",
                      platform="ios",
                      version="0",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME2")],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0)],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
)

LINE_DUPLICATE_REMARKS_UNGROUPED = """
ip access-list extended ACL_NAME
  remark === NAME1
  permit tcp any any eq 1
  remark === NAME2
  permit tcp any any eq 2
  remark === NAME1
  remark text_before_eq_3
  permit tcp any any eq 3
  remark text_after_eq_3
  remark === NAME2
  permit tcp any any eq 4
""".strip()
LINE_DUPLICATE_REMARKS_GROUPED = """
ip access-list extended ACL_NAME
  remark === NAME1
  permit tcp any any eq 1
  remark text_before_eq_3
  permit tcp any any eq 3
  remark text_after_eq_3
  remark === NAME2
  permit tcp any any eq 2
  permit tcp any any eq 4
""".strip()
REQ_DUPLICATE_REMARKS = {
    "line": LINE_DUPLICATE_REMARKS_GROUPED,
    "platform": "ios",
    "version": "0",
    "type": "extended",
    "input": [],
    "output": [],
    "name": "ACL_NAME",
    "items": [{
        "line": "remark === NAME1\n"
                "permit tcp any any eq 1\n"
                "remark text_before_eq_3\n"
                "permit tcp any any eq 3\n"
                "remark text_after_eq_3",
        "platform": "ios",
        "version": "0",
        "type": "extended",
        "name": "=== NAME1",
        "items": [{"line": "remark === NAME1",
                   "platform": "ios",
                   "version": "0",
                   "note": "",
                   "sequence": 0,
                   "action": "remark",
                   "text": "=== NAME1"},
                  {"line": "permit tcp any any eq 1",
                   "platform": "ios",
                   "version": "0",
                   "type": "extended",
                   "note": "",
                   "max_ncwb": 16,
                   "protocol_nr": False,
                   "port_nr": False,
                   "sequence": 0,
                   "action": "permit",
                   "protocol": {"line": "tcp",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol_nr": False,
                                "has_port": True,
                                "name": "tcp",
                                "number": 6},
                   "srcaddr": {"line": "any",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "items": [],
                               "max_ncwb": 16,
                               "type": "any",
                               "addrgroup": "",
                               "ipnet": IPv4Network("0.0.0.0/0"),
                               "prefix": "0.0.0.0/0",
                               "subnet": "0.0.0.0 0.0.0.0",
                               "wildcard": "0.0.0.0 255.255.255.255"},
                   "srcport": {"line": "",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "protocol": "",
                               "port_nr": False,
                               "items": [],
                               "operator": "",
                               "ports": [],
                               "sport": ""},
                   "dstaddr": {"line": "any",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "items": [],
                               "max_ncwb": 16,
                               "type": "any",
                               "addrgroup": "",
                               "ipnet": IPv4Network("0.0.0.0/0"),
                               "prefix": "0.0.0.0/0",
                               "subnet": "0.0.0.0 0.0.0.0",
                               "wildcard": "0.0.0.0 255.255.255.255"},
                   "dstport": {"line": "eq 1",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "protocol": "tcp",
                               "port_nr": False,
                               "items": [1],
                               "operator": "eq",
                               "ports": [1],
                               "sport": "1"},
                   "option": {"line": "",
                              "platform": "ios",
                              "version": "0",
                              "note": "",
                              "flags": [],
                              "logs": []}},
                  {"line": "remark text_before_eq_3",
                   "platform": "ios",
                   "version": "0",
                   "note": "",
                   "sequence": 0,
                   "action": "remark",
                   "text": "text_before_eq_3"},
                  {"line": "permit tcp any any eq 3",
                   "platform": "ios",
                   "version": "0",
                   "type": "extended",
                   "note": "",
                   "max_ncwb": 16,
                   "protocol_nr": False,
                   "port_nr": False,
                   "sequence": 0,
                   "action": "permit",
                   "protocol": {"line": "tcp",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol_nr": False,
                                "has_port": True,
                                "name": "tcp",
                                "number": 6},
                   "srcaddr": {"line": "any",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "items": [],
                               "max_ncwb": 16,
                               "type": "any",
                               "addrgroup": "",
                               "ipnet": IPv4Network("0.0.0.0/0"),
                               "prefix": "0.0.0.0/0",
                               "subnet": "0.0.0.0 0.0.0.0",
                               "wildcard": "0.0.0.0 255.255.255.255"},
                   "srcport": {"line": "",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "protocol": "",
                               "port_nr": False,
                               "items": [],
                               "operator": "",
                               "ports": [],
                               "sport": ""},
                   "dstaddr": {"line": "any",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "items": [],
                               "max_ncwb": 16,
                               "type": "any",
                               "addrgroup": "",
                               "ipnet": IPv4Network("0.0.0.0/0"),
                               "prefix": "0.0.0.0/0",
                               "subnet": "0.0.0.0 0.0.0.0",
                               "wildcard": "0.0.0.0 255.255.255.255"},
                   "dstport": {"line": "eq 3",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "protocol": "tcp",
                               "port_nr": False,
                               "items": [3],
                               "operator": "eq",
                               "ports": [3],
                               "sport": "3"},
                   "option": {"line": "",
                              "platform": "ios",
                              "version": "0",
                              "note": "",
                              "flags": [],
                              "logs": []}},
                  {"line": "remark text_after_eq_3",
                   "platform": "ios",
                   "version": "0",
                   "note": "",
                   "sequence": 0,
                   "action": "remark",
                   "text": "text_after_eq_3"}],
        "group_by": "=== ",
        "note": "",
        "protocol_nr": False,
        "port_nr": False,
        "sequence": 0},
        {"line": "remark === NAME2\n"
                 "permit tcp any any eq 2\n"
                 "permit tcp any any eq 4",
         "platform": "ios",
         "version": "0",
         "type": "extended",
         "name": "=== NAME2",
         "items": [{"line": "remark === NAME2",
                    "platform": "ios",
                    "version": "0",
                    "note": "",
                    "sequence": 0,
                    "action": "remark",
                    "text": "=== NAME2"},
                   {"line": "permit tcp any any eq 2",
                    "platform": "ios",
                    "version": "0",
                    "type": "extended",
                    "note": "",
                    "max_ncwb": 16,
                    "protocol_nr": False,
                    "port_nr": False,
                    "sequence": 0,
                    "action": "permit",
                    "protocol": {"line": "tcp",
                                 "platform": "ios",
                                 "version": "0",
                                 "note": "",
                                 "protocol_nr": False,
                                 "has_port": True,
                                 "name": "tcp",
                                 "number": 6},
                    "srcaddr": {"line": "any",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "items": [],
                                "max_ncwb": 16,
                                "type": "any",
                                "addrgroup": "",
                                "ipnet": IPv4Network("0.0.0.0/0"),
                                "prefix": "0.0.0.0/0",
                                "subnet": "0.0.0.0 0.0.0.0",
                                "wildcard": "0.0.0.0 255.255.255.255"},
                    "srcport": {"line": "",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol": "",
                                "port_nr": False,
                                "items": [],
                                "operator": "",
                                "ports": [],
                                "sport": ""},
                    "dstaddr": {"line": "any",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "items": [],
                                "max_ncwb": 16,
                                "type": "any",
                                "addrgroup": "",
                                "ipnet": IPv4Network("0.0.0.0/0"),
                                "prefix": "0.0.0.0/0",
                                "subnet": "0.0.0.0 0.0.0.0",
                                "wildcard": "0.0.0.0 255.255.255.255"},
                    "dstport": {"line": "eq 2",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol": "tcp",
                                "port_nr": False,
                                "items": [2],
                                "operator": "eq",
                                "ports": [2],
                                "sport": "2"},
                    "option": {"line": "",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "flags": [],
                               "logs": []}},
                   {"line": "permit tcp any any eq 4",
                    "platform": "ios",
                    "version": "0",
                    "type": "extended",
                    "note": "",
                    "max_ncwb": 16,
                    "protocol_nr": False,
                    "port_nr": False,
                    "sequence": 0,
                    "action": "permit",
                    "protocol": {"line": "tcp",
                                 "platform": "ios",
                                 "version": "0",
                                 "note": "",
                                 "protocol_nr": False,
                                 "has_port": True,
                                 "name": "tcp",
                                 "number": 6},
                    "srcaddr": {"line": "any",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "items": [],
                                "max_ncwb": 16,
                                "type": "any",
                                "addrgroup": "",
                                "ipnet": IPv4Network("0.0.0.0/0"),
                                "prefix": "0.0.0.0/0",
                                "subnet": "0.0.0.0 0.0.0.0",
                                "wildcard": "0.0.0.0 255.255.255.255"},
                    "srcport": {"line": "",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol": "",
                                "port_nr": False,
                                "items": [],
                                "operator": "",
                                "ports": [],
                                "sport": ""},
                    "dstaddr": {"line": "any",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "items": [],
                                "max_ncwb": 16,
                                "type": "any",
                                "addrgroup": "",
                                "ipnet": IPv4Network("0.0.0.0/0"),
                                "prefix": "0.0.0.0/0",
                                "subnet": "0.0.0.0 0.0.0.0",
                                "wildcard": "0.0.0.0 255.255.255.255"},
                    "dstport": {"line": "eq 4",
                                "platform": "ios",
                                "version": "0",
                                "note": "",
                                "protocol": "tcp",
                                "port_nr": False,
                                "items": [4],
                                "operator": "eq",
                                "ports": [4],
                                "sport": "4"},
                    "option": {"line": "",
                               "platform": "ios",
                               "version": "0",
                               "note": "",
                               "flags": [],
                               "logs": []}}],
         "group_by": "=== ",
         "note": "",
         "protocol_nr": False,
         "port_nr": False,
         "sequence": 0}],
    "group_by": "=== ",
    "note": "",
    "max_ncwb": 16,
    "indent": "  ",
    "protocol_nr": False,
    "port_nr": False}
