"""Unittest acl.py"""

from ipaddress import IPv4Network

import dictdiffer  # type: ignore

LINE_GROUP_ACEGS = "ip access-list extended ACL_NAME\n" \
                   "  permit icmp any any\n" \
                   "  remark === NAME1\n" \
                   "  permit tcp any any eq 1\n" \
                   "  remark TEXT1\n" \
                   "  remark === NAME2\n" \
                   "  permit tcp any any eq 2\n" \
                   "  deny ip any any"
REQ_GROUPS_ACEGS_D = dict(
    line=LINE_GROUP_ACEGS,
    platform="ios",
    type="extended",
    input=[],
    output=[],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
    name="ACL_NAME",
    items=[
        dict(line="permit icmp any any",
             platform="ios",
             type="extended",
             name="",
             group_by="=== ",
             items=[
                 dict(line="permit icmp any any",
                      platform="ios",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="icmp",
                                    platform="ios",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="icmp",
                                    number=1),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="", platform="ios", note="", flags=[], logs=[]))],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME1\npermit tcp any any eq 1\nremark TEXT1",
             platform="ios",
             type="extended",
             name="=== NAME1",
             group_by="=== ",
             items=[
                 dict(line="remark === NAME1",
                      platform="ios",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME1"),
                 dict(line="permit tcp any any eq 1",
                      platform="ios",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="ios",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="eq 1",
                                   platform="ios",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[1],
                                   operator="eq",
                                   ports=[1],
                                   sport="1"),
                      option=dict(line="", platform="ios", note="", flags=[], logs=[])),
                 dict(line="remark TEXT1",
                      platform="ios",
                      note="",
                      sequence=0,
                      action="remark",
                      text="TEXT1")],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME2\npermit tcp any any eq 2\ndeny ip any any",
             platform="ios",
             type="extended",
             name="=== NAME2",
             group_by="=== ",
             items=[
                 dict(line="remark === NAME2",
                      platform="ios",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME2"),
                 dict(line="permit tcp any any eq 2",
                      platform="ios",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="permit",
                      protocol=dict(line="tcp",
                                    platform="ios",
                                    note="",
                                    protocol_nr=False,
                                    has_port=True,
                                    name="tcp",
                                    number=6),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   type="any",
                                   addrgroup="",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="eq 2",
                                   platform="ios",
                                   note="",
                                   protocol="tcp",
                                   port_nr=False,
                                   items=[2],
                                   operator="eq",
                                   ports=[2],
                                   sport="2"),
                      option=dict(line="", platform="ios", note="", flags=[], logs=[])),
                 dict(line="deny ip any any",
                      platform="ios",
                      type="extended",
                      note="",
                      max_ncwb=16,
                      protocol_nr=False,
                      port_nr=False,
                      sequence=0,
                      action="deny",
                      protocol=dict(line="ip",
                                    platform="ios",
                                    note="",
                                    protocol_nr=False,
                                    has_port=False,
                                    name="ip",
                                    number=0),
                      srcaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      srcport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      dstaddr=dict(line="any",
                                   platform="ios",
                                   items=[],
                                   note="",
                                   max_ncwb=16,
                                   addrgroup="",
                                   type="any",
                                   ipnet=IPv4Network("0.0.0.0/0"),
                                   prefix="0.0.0.0/0",
                                   subnet="0.0.0.0 0.0.0.0",
                                   wildcard="0.0.0.0 255.255.255.255"),
                      dstport=dict(line="",
                                   platform="ios",
                                   note="",
                                   protocol="",
                                   port_nr=False,
                                   items=[],
                                   operator="",
                                   ports=[],
                                   sport=""),
                      option=dict(line="", platform="ios", note="", flags=[], logs=[]))],
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
    ]
)

LINE_GROUP_REMARKS = "ip access-list extended ACL_NAME\n" \
                     "  remark === NAME1\n" \
                     "  remark === NAME2"
REQ_GROUP_REMARKS_D = dict(
    line=LINE_GROUP_REMARKS,
    platform="ios",
    type="extended",
    input=[],
    output=[],
    name="ACL_NAME",
    items=[
        dict(line="remark === NAME1",
             platform="ios",
             type="extended",
             name="=== NAME1",
             items=[
                 dict(line="remark === NAME1",
                      platform="ios",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME1")],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0),
        dict(line="remark === NAME2",
             platform="ios",
             type="extended",
             name="=== NAME2",
             items=[
                 dict(line="remark === NAME2",
                      platform="ios",
                      note="",
                      sequence=0,
                      action="remark",
                      text="=== NAME2")],
             group_by="=== ",
             note="",
             protocol_nr=False,
             port_nr=False,
             sequence=0)],
    group_by="=== ",
    note="",
    max_ncwb=16,
    indent="  ",
    protocol_nr=False,
    port_nr=False,
)
