"""Unittest ace.py"""

from ipaddress import IPv4Network

REQ_COPY1 = dict(
    line="20 deny udp any eq 80 10.0.0.0/24 range 2 3",
    platform="nxos",
    sequence=20,
    action="deny",
    protocol="udp",
    srcaddr="any",
    srcport="eq 80",
    dstaddr="10.0.0.0/24",
    dstport="range 2 3",
    option="",
    protocol_nr=False,
    port_nr=False,
    note="b",
)
REQ_COPY2 = dict(
    line="10 permit tcp host 10.0.0.1 10.0.0.0 0.0.0.3 eq 80 443 log",
    platform="ios",
    sequence=10,
    action="permit",
    protocol="tcp",
    srcaddr="host 10.0.0.1",
    srcport="",
    dstaddr="10.0.0.0 0.0.0.3",
    dstport="eq 80 443",
    option="log",
    protocol_nr=True,
    port_nr=True,
    note="a",
)
REQ_DATA1 = dict(
    line="10 permit tcp host 10.0.0.1 10.0.0.0 0.0.0.3 eq www 443 log",
    platform="ios",
    version="0",
    type="extended",
    sequence=10,
    action="permit",
    protocol=dict(line="tcp",
                  platform="ios",
                  version="0",
                  note="",
                  protocol_nr=False,
                  has_port=True,
                  name="tcp",
                  number=6),
    srcaddr=dict(line="host 10.0.0.1",
                 platform="ios",
                 version="0",
                 items=[],
                 note="",
                 max_ncwb=16,
                 type="host",
                 addrgroup="",
                 ipnet=IPv4Network("10.0.0.1/32"),
                 prefix="10.0.0.1/32",
                 subnet="10.0.0.1 255.255.255.255",
                 wildcard="10.0.0.1 0.0.0.0"),
    srcport=dict(line="",
                 platform="ios",
                 version="0",
                 protocol="",
                 note="",
                 port_nr=False,
                 items=[],
                 operator="",
                 ports=[],
                 sport=""),
    dstaddr=dict(line="10.0.0.0 0.0.0.3",
                 platform="ios",
                 version="0",
                 items=[],
                 note="",
                 max_ncwb=16,
                 type="wildcard",
                 addrgroup="",
                 ipnet=IPv4Network("10.0.0.0/30"),
                 prefix="10.0.0.0/30",
                 subnet="10.0.0.0 255.255.255.252",
                 wildcard="10.0.0.0 0.0.0.3"),
    dstport=dict(line="eq www 443",
                 platform="ios",
                 version="0",
                 protocol="tcp",
                 note="",
                 port_nr=False,
                 items=[80, 443],
                 operator="eq",
                 ports=[80, 443],
                 sport="80,443"),
    option=dict(line="log",
                platform="ios",
                version="0",
                note="",
                flags=[],
                logs=["log"]),
    note="a",
    max_ncwb=16,
    protocol_nr=False,
    port_nr=False,
)
